#!/bin/sh
setup_ssid()
{
    local r="radio$1"
    
    if ! uci show wireless.${r} >/dev/null 2>&1; then
        return
    fi
    local s="wlan$1"
    logger "default-wifi: setup $1's ssid"
    local mac=`ifconfig ${s} | grep "HWaddr" | awk '{print $5}'`
    local wifimac=`echo ${mac}|awk -F ":" '{print $4""$5""$6 }'|tr A-Z a-z|cut -c4-`
    # uci set wireless.${r}.disabled=0
    uci set wireless.${r}.country=CN
    # uci set wireless.${r}.channel=149
    if [ `uci get wireless.${r}.channel` -lt 14 ]; then
        uci set wireless.${r}.channel=11
        uci set wireless.default_${r}.ssid=Ez-2.4G
    else
        uci set wireless.${r}.channel=149
        uci set wireless.default_${r}.ssid=Ez-5G
    fi
    uci set wireless.default_${r}.encryption='psk2'
    uci set wireless.default_${r}.key='12345678'
    uci commit
}
WIFI_NUM=`find /sys/class/net/ -name wlan* | wc -l`
if [ ${WIFI_NUM} -gt 0 ]; then
    # update /etc/config/wireless
    for i in `seq 0 ${WIFI_NUM}`; do
        setup_ssid ${i}
    done
fi
uci set luci.main.lang=auto
uci commit luci
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system
uci set network.@globals[0].ula_prefix=''
uci set network.lan.delegate='0'
#4g
uci set network.4G=interface
uci set network.4G._orig_ifname='wwan0'
uci set network.4G._orig_bridge='false'
uci set network.4G.proto='qmi'
uci set network.4G.device='/dev/cdc-wdm0'
uci set network.4G.auth='none'
uci commit network
uci add_list firewall.@zone[1].network='4G'
uci commit firewall

ln -sf /sbin/ip /usr/bin/ip

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
uci set wireless.radio0.disabled=0
uci set wireless.radio1.disabled=0
uci commit wireless
wifi up
sed -i 's,# PermitRootLogin.*,PermitRootLogin yes,g'  /etc/ssh/sshd_config
sed -i 's,# PasswordAuthentication.*,PasswordAuthentication yes,g'  /etc/ssh/sshd_config 
/etc/init.d/sshd restart
sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='Ez-R3.0'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='EzOpWrt '" >> /etc/openwrt_release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua
echo 'hsts=0' > /root/.wgetrc
rm -rf /tmp/luci-*

exit 0
